### ISSUE TITLE
Problem with additional permissions for cookie management and network settings

### ISSUE THREAD

**Issue by entepe85** [Manvel/Privacy-Manager#23]
Chrome version: 70.0.3504.0 (canary)
Operating system: macOS High Sierra (10.13.4)

Upon inspecting the privacy manager popup with Chrome DevTools I noticed the following error in the console when clicking the Additional Permissions switch:
`Unchecked runtime.lastError: This function must be called during a user gesture`

That error originates from popup.html:1

I am therefore unfortunately unable to grant additional permissions.

**Comment by Manvel** [comment]
Hi @entepe85 Sorry, for late reply, this went out of my radar.

I'm not able to reproduce that on Chrome v70 High Sierra 10.13.6.

Can you please let me know if this issue still exists, I'll try to followup on that,

Thanks in advance.

**Comment by entepe85** [comment]
Hey @Manvel Don't worry, I got a bit overwhelmed by work myself.

I actually just tried to reproduce the described behaviour on Chromium 69.0.3497.81 and the extension works as expected and doesn't throw any errors. I will therefore close this issue.

**Comment by Manvel** [comment]
Please let me know if that happens again, lately a [fix landed](https://github.com/Manvel/Privacy-Manager/issues/24) related to Chrome v70, might be somehow connected.

Thanks.
