### ISSUE TITLE
No longer works in Chrome v70 on windows

### ISSUE THREAD

**Issue by adolfintel** [Manvel/Privacy-Manager#24]
Here's what happens when I try to use it:
![image](https://user-images.githubusercontent.com/16307689/45342474-62b09500-b59e-11e8-99ff-cf2c7c7b1eca.png)

If I click around the tabs, it shows the UI again. If I click on remove all it doesn't do anything. The list of options that's supposed to be below it is also missing.
![image](https://user-images.githubusercontent.com/16307689/45342592-b622e300-b59e-11e8-8f40-3788b8149696.png)

These errors show up in the console
![image](https://user-images.githubusercontent.com/16307689/45342628-cd61d080-b59e-11e8-86ca-50cfa0a19e43.png)

**Comment by Manvel** [comment]
Thanks for reporting @adolfintel 

Interesting works fine on my side, I have Chrome V69.0.3497.81 on Mac.

I assume you are running Privacy Manager, on other OS ?

**Comment by adolfintel** [comment]
Sorry I just noticed that it was version 70 that broke it. Download the latest dev builds and see for yourself.

This is on Windows 10 64bit, using the official builds. Let me know if you need any more info or test done

On September 11, 2018 1:34:56 PM GMT+02:00, Manvel Saroyan <notifications@github.com> wrote:
>Thanks for reporting @adolfintel 
>
>Interesting works fine on my side, I have Chrome V69.0.3497.81 on Mac.
>
>I assume you are running Privacy Manager, on other OS ? 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Manvel/Privacy-Manager/issues/24#issuecomment-420242268

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Manvel** [comment]
Ohh I see, I'll try to reproduce it later today or latest tomorrow and come back to you, after. Thanks.

**Comment by Manvel** [comment]
@adolfintel Seems like this is only reproducible on Windows, I couldn't reproduce that on my Mac with Chrome V70. So basically this happens when local storage setters and getters are assigned to the variable.

```
const setStorage = chrome.storage.local.set;
const getStorage = chrome.storage.local.get;

setStorage({key: value})
```

Basically having a wrapper fixes the issue, smth like:
```
const setStorage = (data, callback) =>
{
  chrome.storage.local.set(data, callback);
};
```

I'll rollout an update to fix the issue for you and then followup and create a Chrome bug, after I prepare a test case and check across different Chrome versions and Web Extensions.

I'll try to rollout the update later today (Couldn't get to this earlier as I was at work).

Thanks for reporting this.

**Comment by adolfintel** [comment]
Great, thanks

On September 11, 2018 9:04:59 PM GMT+02:00, Manvel Saroyan <notifications@github.com> wrote:
>@adolfintel Seems like this is only reproducible on Windows, I couldn't
>reproduce that on my Mac with Chrome V70. So basically this happens
>when local storage setters and getters are assigned to the variable.
>
>```
>const setStorage = chrome.storage.local.set;
>const getStorage = chrome.storage.local.get;
>
>setStorage({key: value})
>```
>
>Basically having a wrapper fixes the issue, smth like:
>```
>const setStorage = (data, callback) =>
>{
>  chrome.storage.local.set(data, callback);
>};
>```
>
>I'll rollout an update to fix the issue for you and then followup and
>create a Chrome bug, after I prepare a test case and check across
>different Chrome versions and Web Extensions.
>
>I'll try to rollout the update later today (Couldn't get to this
>earlier as I was at work).
>
>Thanks for reporting this.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Manvel/Privacy-Manager/issues/24#issuecomment-420386130

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Manvel** [comment]
@adolfintel release v3.2.2 is out and published in the Chrome Web Store.

I've also created a followup not to forget to file a bug -> https://github.com/Manvel/Privacy-Manager/issues/26 

May I ask you to check when you have time, if the new version of Privacy Manager fixes the issue for you, so I can close this ticket.

Thanks again for noticing this issue.

**Comment by adolfintel** [comment]
Yes, it works again now. Thanks!
