### ISSUE TITLE
Add Privacy Policy and move Webstore Details from Overview

### ISSUE THREAD

**Issue by mikhaelkh** [Manvel/Privacy-Manager#41]
Webstore Details are present in Overview but absent in respective places - https://crxcavator.io/report/giccehglhacakcfemddmfhdkahamfcmd/3.4.1

```
Email - saroyanm@gmail.com
Privacy Policy - ?, weird that a privacy related extension doesn't have a privacy policy specified
Support Site - https://github.com/Manvel/Privacy-Manager#reporting-bugs-suggestions-and-questions
Website - https://github.com/Manvel/Privacy-Manager
```

**Comment by Manvel** [comment]
Thanks @mikhaelkh for the issue:

> https://crxcavator.io

Haven't heard about current resource, will check to find out how it gathers data and update the extension description accordingly.

> but absent in respective places

Not sure if there are many places to specify most of the resources other than Overview, at least in CWS, I have updated some info in the general dashboard, hope this now will be accessible.

> Privacy Policy - ?, weird that a privacy related extension doesn't have a privacy policy specified
S

Agree this should have been tackled long time ago, the plan was to add that info into the website -> which is yet under development, [engine for website is created](https://cmints.io/), but haven't get enough time to finish the website.

I'll  write PP, add to the Github meanwhile and update link in the CWS overview.

> Site - https://github.com/Manvel/Privacy-Manager#reporting-bugs-suggestions-and-questions
Website - https://github.com/Manvel/Privacy-Manager

Agree, done.

> Email - saroyanm@gmail.com

Have added this info into the Developer dashboard, hope that will be accessible now through the posted extensions as well, there is no dedicated place nor in manifest, nor in CWS extension page where this field can be specified directly for specific extension though.

I'll wait to see if the added data is enough and add PP to Github before closing this. Need to see what kind of data CWS collects, before writing PP. Extension itself doesn't collect any data.

**Comment by Manvel** [comment]
Added privacy policy -> https://github.com/Manvel/Privacy-Manager/blob/master/privacy-policy.md here and added to the listing details, but there is no way to add Privacy Policy to a listing, but rather whole profile, which makes no sense for now, unless I create a Privacy Policy for each of my listings and host on my blog or create a whole separate profile for Privacy Manager.

Any ideas/suggestions are welcome.

**Comment by mikhaelkh** [comment]
https://developer.chrome.com/webstore/user_data

**Comment by Manvel** [comment]
> https://developer.chrome.com/webstore/user_data

Yes I've seen that resource. According to that resource and considering that Privacy Manager Extension doesn't handle/collect any data:
```
You have no special or new obligations under the User Data Policy"
```
Seems like current solution is least/quickest that can be done now, to make compliant with the guide. As soon the website is ready things will be clear. I'll add some "about tab"/modal into the UI as well to provide links and info(s), also link to PP probably, created a separate issue for that(but can't say when this will be ready) -> https://github.com/Manvel/Privacy-Manager/issues/42 

> I think you don't need to specify about the data that is collected by CWS, it is handled by Google Chrome Privacy Policy

I thought it would be nice to have that info there, to make users informed about that, but you are right, I may remove that info.

Thanks for your help @mikhaelkh I'll close this issue for now, let me know if there is anything I didn't get right or needs to be updated.

**Comment by Manvel** [comment]
Also any relevant PR is welcome.

**Comment by mikhaelkh** [comment]
Explicitly stating that extension does not collect any data is better than nothing. No need for your own website, link to GitHub will be enough:

> 4. My Product DOES NOT handle sensitive or personal data. What do I need to do?

> You have no special or new obligations under the User Data Policy. Consistent with the prior policy and the Developer Terms of Service, Products must disclose their collection, use, and sharing of user data. You can describe your privacy practices in any way users could easily find when installing or using your Product. For example, you could describe them in the Chrome Web Store description or via your Product’s interface. **You could also choose to include a link to a privacy policy on your Product’s listing.**


Like e.g. [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) has a link to [Privacy Policy](https://github.com/gorhill/uBlock/wiki/Privacy-policy), that is what I meant.

**Comment by Manvel** [comment]
> Like e.g. uBlock Origin has a link to Privacy Policy in Additional Information, that is what I meant.

As also mentioned above, there is no way(or I just don't know about the way) to add "Privacy Policy" link to only one listing in the Chrome Web Store, the only way is to add "Privacy Policy" link to whole user account, not only 1 listing(ex.: Privacy Manager).

So basically if I do same way, then all my extension uploaded to CWS will share same Privacy Policy. So in order to do same as it's done in your example link, I'll need to create a separate account only for Privacy Manager, which is not what I want to do. Alternatively I'll need to create a Global Privacy Policy for all my extensions hosted in Chrome Web Store, which is again not ideal.

I would assume that's the reason why a lot of extension don't have Privacy Policy field available in the additional info section. This sounds like a limitation of Chrome Web Store.

Hope I could describe the issue better. Also hope that I just missing something, though I can't find any way from the listing itself to add Privacy Policy link.

**Comment by mikhaelkh** [comment]
You're right, all of gorhill's extensions (uBlock Origin, uMatrix, etc.) share the same PP, I didn't notice it before. Thanks for taking the time to thoroughly explaining it.
